# Generated by Django 2.1.1 on 2018-09-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180912_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdlOcorrencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.TextField(blank=True, verbose_name='Solicitação')),
                ('datacriacao', models.DateTimeField(auto_now_add=True)),
                ('dataalteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mdlsituacao',
            options={'verbose_name': 'Situação', 'verbose_name_plural': 'Situações'},
        ),
        migrations.AddField(
            model_name='mdlocorrencias',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mdlSituacao'),
        ),
    ]
