# Generated by Django 2.1.1 on 2018-09-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180913_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdlocorrencias',
            options={'verbose_name': 'Ocôrrencia', 'verbose_name_plural': 'Ocôrrencia'},
        ),
        migrations.AlterField(
            model_name='mdlocorrencias',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mdlSituacao', verbose_name='Situação'),
        ),
    ]
